apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceAccountsRole
rules:
- apiGroups: ["", "apps", "autoscaling", "batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  # Include all verbs except 'use' to prevent the usage of any pod security policy
  # https://stackoverflow.com/questions/57720681/why-is-my-podsecuritypolicy-applied-even-if-i-dont-have-access
  #verbs: ["*"]
  verbs: ["create", "get", "watch", "list", "patch", "delete", "deletecollection", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: serviceAccountsRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: serviceAccountsRole
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:masters
  apiGroup: rbac.authorization.k8s.io
