apiVersion: apps/v1
kind: Deployment
metadata:
  name: education-app
  namespace: education-ns
spec:
  selector:
    matchLabels:
      app: education
  replicas: 3
  template:
    metadata:
      labels:
        app: education
    spec:
      serviceAccountName: education-sa
      containers:
      - name: education
        image: "asia.gcr.io/rds-rnd-project/education:latest"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
