---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testing
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testing
  namespace: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testing
subjects:
- kind: ServiceAccount
  name: testing
  namespace: dev