apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: cert-manager
  name: cert-manager
  namespace: cert-manager
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: metrics
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_endpoint_node_name
      regex: ^gke-(\w+-\w+).+$
      targetLabel: cluster_name
      replacement: $1
      action: replace
    - sourceLabels:
      - __meta_kubernetes_endpoint_node_name
      targetLabel: node
      action: replace
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
