apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    name: event-exporter
  name: event-exporter
  namespace: monitoring
spec:
  ports:
    - name: metrics
      port: 9102
      targetPort: 9102
  selector:
    app: event-exporter
