bases:
  - ../base

resources:
  - ../../../components/kube-state-metrics

patchesStrategicMerge:
- |-
  apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    name: kube-state-metrics
    namespace: monitoring
  $patch: delete
