---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: hack-for-applicationset-controller
spec:
  fsGroup:
    rule: RunAsAny
  hostPorts:
    - max: 0
      min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - configMap
    - emptyDir
    - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-psp:applicationset-controller
  namespace: argocd
rules:
  - apiGroups:
      - policy
    resourceNames:
      - hack-for-applicationset-controller
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-psp:applicationset-controller-binding
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-psp:applicationset-controller
subjects:
  - kind: ServiceAccount
    name: argocd-applicationset-controller
    namespace: argocd
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
  - kind: ServiceAccount
    name: argocd-dex-server
    namespace: argocd
  - kind: ServiceAccount
    name: argocd-notifications-controller
    namespace: argocd
  - kind: ServiceAccount
    name: argocd-redis
    namespace: argocd
  - kind: ServiceAccount
    name: argocd-repo-server
    namespace: argocd
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd