- job_name: 'monitoring/cadvisor/0'
  scheme: https
  scrape_interval: 15s
  honor_labels: true
  honor_timestamps: true
  metrics_path: /metrics/cadvisor
  tls_config:
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
    namespaces:
      names:
      - kube-system
  relabel_configs:
  - source_labels: [__meta_kubernetes_node_name]
    regex: ^gke-(\w+-\w+).+$
    target_label: cluster_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_node_name]
    target_label: node
  - source_labels: [__meta_kubernetes_node_address_InternalIP]
    target_label: node_ip
  - source_labels: [__meta_kubernetes_node_label_beta_kubernetes_io_instance_type]
    target_label: node_type
  metric_relabel_configs:
  - source_labels: [__name__]
    regex: container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)
    replacement: $1
    action: drop

- job_name: 'monitoring/kubelet/0'
  scheme: https
  scrape_interval: 15s
  honor_labels: true
  honor_timestamps: true
  metrics_path: /metrics
  tls_config:
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
    namespaces:
      names:
      - kube-system
  relabel_configs:
  - source_labels: [__meta_kubernetes_node_name]
    regex: ^gke-(\w+-\w+).+$
    target_label: cluster_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_node_name]
    target_label: node
  - source_labels: [__meta_kubernetes_node_address_InternalIP]
    target_label: node_ip
  - source_labels: [__meta_kubernetes_node_label_beta_kubernetes_io_instance_type]
    target_label: node_type
  metric_relabel_configs:
  - source_labels: [__name__]
    regex: ^kubelet_volume.*$
    replacement: $1
    action: keep
