apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar-k8s
  namespace: monitoring
  labels:
    app: thanos-sidecar-k8s
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    prometheus: k8s
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
