apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-disk
  namespace: jenkins
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi