apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    name: node-exporter
    version: 0.15.2
  name: node-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 9100
  selector:
    name: node-exporter
  sessionAffinity: None
  type: ClusterIP
